### ISSUE TITLE
Noteコンポーネントを実装する

### ISSUE THREAD

**Issue by da-yone** [MyBrotherJake/cloud-note-app#16]
## やりたいこと

Noteコンポーネントを実装し、以下の機能を実現する

- ノート・フォルダ一覧表示
- ノート名クリック時にノート内容をエディタ部分に表示

## 補足

- ノート一覧の取得APIのURLは `http://localhost:4000/notes`
- ノート詳細の取得APIのURLは `http://localhost:4000/notes/[note-id]`
- ノートの新規作成機能及びAPIの実装は別issueで対応するため、ノートはダミーデータを使用すること

## TODO

- [x]  現在index.jsに配置しているコードを、コンポーネントごとの処理に分割する
- [x] `NoteTitle.jsx` (ノート名), `NoteBody.jsx` (ノートの内容) からなる `Note.jsx` (エディタ画面) を作成
- [x] `NoteList.jsx` を 作成し `NoteListItems.jsx` (一覧表示) だけを実装
- [x]  フォルダIDとフォルダ名及びノートIDとノート名、内容を含めた、ダミーデータを作成(コンポーネント内に記述)
- [x] フォルダID, フォルダ名を取得
- [x] フォルダID を キーに、ノートID と ノート名 を取得
- [x] 一覧にフォルダ名とノート名だけを表示
- [x] クリックされたノート名のIDを元に、内容を取得 
- [x] ノート内容をエディタに表示
